{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
spec:
  selector:
    matchLabels:
      app: {{ template "cp-schema-registry.name" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
