apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if .Values.ui.annotations }}
  annotations: {{ toYaml .Values.ui.annotations | nindent 4 }}
  {{- end}}
  labels:
    app: {{ template "cp-schema-registry.fullname" . }}
  {{- if .Values.ui.labels }}
  {{ toYaml .Values.ui.labels | indent 4}}
  {{- end}}
  name: {{ template "cp-schema-registry.fullname" . }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cp-schema-registry.fullname" . }}
      service: schema-registry-ui
  template:
    metadata:
      annotations:
      {{- if .Values.ui.annotations }}
      {{ toYaml .Values.ui.annotations | indent 6 }}
      {{ end }}
      labels:
        app: {{ template "cp-schema-registry.fullname" . }}
        service: schema-registry-ui
      {{- if .Values.ui.labels }}
      {{ toYaml .Values.ui.labels | indent 8}}
      {{- end}}
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        runAsNonRoot: true
      containers:
        - env:
            - name: PROXY
              value: "true"
            - name: SCHEMAREGISTRY_URL
              value: {{ template  "cp-schema-registry.connectUrlValue" . }}
          image: landoop/schema-registry-ui
          imagePullPolicy: IfNotPresent
          name: {{ template "cp-schema-registry.fullname" . }}-ui
          ports:
            - containerPort: 8000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.ui.annotations }}
  annotations: {{ toYaml .Values.ui.annotations | nindent 4 }}
  {{- end}}
  labels:
    app: {{ template "cp-schema-registry.fullname" . }}
  {{- if .Values.ui.labels }}
  {{ toYaml .Values.ui.labels | indent 4 }}
  {{- end}}
  name: {{ template "cp-schema-registry.fullname" . }}-ui
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ template "cp-schema-registry.fullname" . }}
    service: schema-registry-ui
  type: ClusterIP
